image:
  repository: ghcr.io/ynotnauk/antcd
  tag: 0.1.1
  pullPolicy: IfNotPresent

git:
  repo: "https://github.com/ynotnauk/antcd.git"
  branch: "main"
  path: "./manifests"
  pollInterval: "30s"
  token: ""

service:
  type: ClusterIP
  port: 8080

targetNamespace: "default"
