server:
  port: 8080
  webhookSecret: "secret"
repos:
  - name: antcd
    url: "https://github.com/ynotnauk/antcd.git"
    branch: "main"
    pollInterval: "10s"
    targets:
      - name: test-app
        type: manifests
        path: ./manifests
