apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
        - name: antcd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--config", "/etc/antcd/config.yaml"]
          ports:
            - containerPort: {{ .Values.server.port }}
          {{- if or .Values.git.token .Values.server.webhookSecret }}
          env:
            {{- if .Values.git.token }}
            - name: ANTCD_GIT_TOKEN
              value: {{ .Values.git.token | quote }}
            {{- end }}
            {{- if .Values.server.webhookSecret }}
            - name: ANTCD_WEBHOOK_SECRET
              value: {{ .Values.server.webhookSecret | quote }}
            {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.server.port }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/antcd
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
