{{- $data := dict }}
{{- if .Values.server.webhookSecret }}
{{- $_ := set $data "webhook-secret" .Values.server.webhookSecret }}
{{- end }}
{{- range $i, $repo := .Values.repos }}
{{- if $repo.token }}
{{- $_ := set $data (printf "git-token-%d" $i) $repo.token }}
{{- end }}
{{- end }}
{{- if $data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  {{- toYaml $data | nindent 2 }}
{{- end }}
